### ISSUE TITLE
Webpage Design

### ISSUE THREAD

**Issue by JacobErnst98** [Dutchess228Group2/WheelsOverTheHudson#1]
http://www.droid-life.com/  Menu bar
http://www.sony.com/ boxes

**Comment by JacobErnst98** [comment]
The boxes from sony's website are easy to make let's start there for the body of the wesite.

**Comment by mthomaswilliams** [comment]
I'm a little confused as to how exactly we would like the scrolling nav bar to function. Do we want it to stay at the top as you scroll up or down, or hide when you scroll down and reappear when user scrolls up?

**Comment by JacobErnst98** [comment]
look at the link sent in the first comment of this discussion for reference.  Don't fell like everything has to be perfect right away. You are always encouraged to put code on the github even if its not totally functioning. Someone else can help fix any hiccups.

**Comment by Doyin1** [comment]
i did a basic nav bar without using java script that will stay fixed at the top while the user scrolls is that okay?

**Comment by Doyin1** [comment]
/* this is the css code for a fixed navigation menu that follows you as you scroll down */
ul {
    position: auto;
    top: auto;
    width: 100%;
}

**Comment by JacobErnst98** [comment]
There is now a separated nav bar issue.

**Comment by deycallmesmoke** [comment]
the design for the site is amazing
