### ISSUE TITLE
Fancy boxes for homepage.

### ISSUE THREAD

**Issue by JacobErnst98** [Dutchess228Group2/WheelsOverTheHudson#15]
We want boxes that look like sony's website. Whoever is doing this issue does not need to worry about the information in the boxes just how the boxes display when tiled.

**Comment by mthomaswilliams** [comment]
I'd like to be assigned this

**Comment by Doyin1** [comment]
@JacobErnst98 I would like to be assigned this too

**Comment by JacobErnst98** [comment]
Before @Doyin1 starts any work on this, @mthomaswilliams are you ready to do a pull request yet?

**Comment by Doyin1** [comment]
i'm with him right now. he doesn't have the work currently on him

**Comment by JacobErnst98** [comment]
If he has any work at home he should upload it so we don't have version mismatches
