### ISSUE TITLE
Interactive tiles

### ISSUE THREAD

**Issue by Doyin1** [Dutchess228Group2/WheelsOverTheHudson#18]
https://github.com/tholman/tileJs/blob/master/index.html

This is a link to a page on github that did tiles that do a movement when hovered/clicked on

here's the website its displayed on
http://tholman.com/projects/tile-js/

**Comment by Doyin1** [comment]
Also this is great refernce for tiles 
http://cssdeck.com/labs/windows-8-metro-tiles-with-css3


for making the tiles "clickable" to go to a webpage here's an example foor anyone who needs this

<telerik:RadContentTemplateTile runat="server" ID="RadContentTemplateTile1" NavigateUrl="some-page.aspx">
    <ContentTemplate>
        <a href="A">Page A</a>
        <br />
        <a href="B">B</a>
    </ContentTemplate>
</telerik:RadContentTemplateTile>

**Comment by Doyin1** [comment]
http://www.telerik.com/forums/is-it-possible-to-put-links-in-tiles

for putiing links on the tiles

**Comment by JacobErnst98** [comment]
Have you done any testing with this source?

**Comment by Doyin1** [comment]
not really. I was just reading the code and was thinking of using it as a guideline.

The github one, I could view the code he used on github
and with the other one you can see the resulting image right next to the code

**Comment by mthomaswilliams** [comment]
@JacobErnst98 I'd llke to be assigned this.
