### ISSUE TITLE
Selecting fonts

### ISSUE THREAD

**Issue by JacobErnst98** [Dutchess228Group2/WheelsOverTheHudson#2]
https://fonts.google.com/ is a great way to get fonts and we don't have to host the fonts.

**Comment by mthomaswilliams** [comment]
I like Muri, Maven Pro, or just anything sans serif really. I like the modern look of these and I feel with the modern design of our site it would pair well

**Comment by JacobErnst98** [comment]
If you link the fonts you like in this issue thread i can start to make css classes for our various sections. Just note next to each font what part of the website it should be used in.

**Comment by JacobErnst98** [comment]
I have picked some fonts and placed them in the index.css file
